# Generated by Django 6.0.1 on 2026-01-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_postable', models.BooleanField(default=True, help_text='If false, cannot be used for financial postings')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='projects.projectcostcenter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Cost Center',
                'verbose_name_plural': 'Project Cost Centers',
                'ordering': ('code',),
                'unique_together': {('project', 'code')},
            },
        ),
    ]
