# Generated by Django 6.0.1 on 2026-01-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_fiscalyear_is_closed_alter_documentsequence_prefix'),
        ('finance', '0003_journalline_cost_center_journalline_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ap_account', models.ForeignKey(help_text='Accounts Payable control account', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='finance.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.company')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ('code',),
                'unique_together': {('company', 'code')},
            },
        ),
    ]
