# Generated by Django 6.0.1 on 2026-01-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_journalline_cost_center_journalline_project'),
        ('procurement', '0002_purchaserequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ('-created_at',), 'verbose_name': 'Purchase Request', 'verbose_name_plural': 'Purchase Requests'},
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total amount (used for PO)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_date',
            field=models.DateField(blank=True, help_text='Date when the purchase request was created', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ap_account',
            field=models.ForeignKey(help_text='Accounts Payable control account (e.g. 2100)', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(help_text='Vendor unique code within the company', max_length=50),
        ),
    ]
