# Generated by Django 6.0.1 on 2026-01-10 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings_accounting_trigger'),
        ('procurement', '0005_alter_purchaserequest_estimated_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, editable=False, max_length=50)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='core.company')),
                ('goods_receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_invoice', to='procurement.goodsreceipt')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Invoice',
                'verbose_name_plural': 'Vendor Invoices',
            },
        ),
    ]
