# Generated by Django 6.0.1 on 2026-01-09 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.CharField(default='SAR', help_text='ISO currency code (e.g., SAR, USD)', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('document_start_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
