# Generated by Django 6.0.1 on 2026-01-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documenttype_documentsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='prefix',
            field=models.CharField(help_text='Example: BURJ-JV-2026', max_length=50),
        ),
    ]
