# Generated by Django 6.0.1 on 2026-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fiscalyear_is_closed_alter_documentsequence_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='accounting_trigger',
            field=models.CharField(choices=[('GR', 'Goods Receipt'), ('VI', 'Vendor Invoice'), ('BOTH', 'Goods Receipt & Invoice')], default='BOTH', help_text='Defines when accounting entries are generated', max_length=10),
        ),
    ]
